### ISSUE TITLE
support x64?

### ISSUE THREAD

**Issue by darkr4y** [PassingTheKnowledge/Ganxo#2]
is this project only support for x86?

**Comment by lallousx86** [comment]
Not at the moment, but in two month at most yes.

**Comment by darkr4y** [comment]
https://github.com/shmuelyr/CaptainHook
 
Recommend a project maybe you can be used as a reference :)

**Comment by lallousx86** [comment]
Hehe, thanks for sharing. I like its name. Where's the Peter Pan project?

I did not know it exists. Honestly, I prefer not to read its code until I implement my own style / support for x64. What I have to implement is just a couple of functions and I am set.
